from pathlib import Path

MODEL_VERSION = "model_2025_09_23_1e09"

MODEL_PATH = Path(__file__).parent / f"model_files/{MODEL_VERSION}.json"

JOINING_MATCH_WEIGHT_THRESHOLD = 24
FRACTURE_MATCH_WEIGHT_THRESHOLD = 18
IS_CLUSTER_VALID_MATCH_WEIGHT_THRESHOLD = 18
