from pathlib import Path

MODEL_VERSION = "model_2026_02_23_1e09"

MODEL_PATH = Path(__file__).parent / f"model_files/{MODEL_VERSION}.json"

JOINING_MATCH_WEIGHT_THRESHOLD = 24
FRACTURE_MATCH_WEIGHT_THRESHOLD = 18
IS_CLUSTER_VALID_MATCH_WEIGHT_THRESHOLD = 18
POSSIBLE_TWINS_SIMILARITY_FLAG_THRESHOLD = 12
POSSIBLE_TWINS_ASSIGNED_MATCH_WEIGHT = -5
POSSIBLE_TWINS_ASSIGNED_MATCH_PROBABILITY = (
    2**POSSIBLE_TWINS_ASSIGNED_MATCH_WEIGHT / (2**POSSIBLE_TWINS_ASSIGNED_MATCH_WEIGHT + 1)
)
