services:

  postgres-hmpps-person-match:
    container_name: postgres-hpm
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    networks:
      - hmpps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  hmpps-person-match:
    container_name: hmpps-person-match
    image: hmpps-person-match:latest
    networks:
      - hmpps
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_NUMBER: local
        GIT_REF: ref
        GIT_BRANCH: branch
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: dev
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres-hmpps-person-match
      DB_SSL_ENABLED: False
    depends_on: 
      - postgres-hmpps-person-match
    ports: 
      - 5000:5000

networks:
  hmpps: