services:

  postgres-hmpps-person-match:
    container_name: postgres-hpm
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    networks:
      - hmpps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql
    healthcheck:
      test: pg_isready -U root -d postgres
      start_period: 5s
      start_interval: 0.2s
      interval: 30s
      timeout: 3s
      retries: 3

  hmpps-person-match:
    container_name: hmpps-person-match
    image: hmpps-person-match:latest
    command: |
      sh -c "/app/.venv/bin/python -m pip install --no-cache-dir debugpy &&
             python -m debugpy --listen 0.0.0.0:5678 -m uvicorn asgi:app --host 0.0.0.0 --port 5000 --reload --log-level debug"
    networks:
      - hmpps
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_NUMBER: local
        GIT_REF: ref
        GIT_BRANCH: branch
    volumes:
      - ./hmpps_person_match:/app/hmpps_person_match/
      - ./hmpps_cpr_splink:/app/hmpps_cpr_splink/
    environment: &database_config
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: dev
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres-hmpps-person-match
      DB_SSL_ENABLED: False
    depends_on: 
      migrations:
          condition: service_completed_successfully
    ports: 
      - 5000:5000
      - 5678:5678

  migrations:
    build: .
    container_name: db-migrations
    command: alembic upgrade head
    networks:
      - hmpps
    environment:
      <<: *database_config
    depends_on:
      postgres-hmpps-person-match:
        condition: service_healthy

networks:
  hmpps: