generic-service:
  nameOverride: hmpps-person-match

  replicaCount: 2

  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi

  image:
    repository: ghcr.io/ministryofjustice/hmpps-person-match
    tag: latest # override at deployment time
    port: 5000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-person-record-cert
    path: /

  imagePullSecrets:
    - name: dockerconfigjson-github-com

  livenessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 10
  readinessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 10

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  namespace_secrets:
    hmpps-person-match:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    hmpps-person-match-rds-instance-output:
      DATABASE_NAME: "database_name"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_HOST: "rds_instance_address"

  env:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-person-match
  alertSeverity: hmpps-person-record-alerts-prod
