---
generic-service:

  autoscaling:
    minReplicas: 1
    maxReplicas: 1

  scheduledDowntime:
    enabled: true

  ingress:
    enabled: false

  env:
    OAUTH_BASE_URL: https://sign-in-dev.hmpps.service.justice.gov.uk
    OAUTH_ISSUER_URL_KEY: https://sign-in-dev.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-630cc18efc9725ba: "hmpps-person-match-database"

cron:
  generateTermFrequencies: "0 12 * * 1-5"