---
generic-service:
  ingress:
    host: hmpps-person-match.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-person-record-cert-secret

  env:
    OAUTH_BASE_URL: https://sign-in.hmpps.service.justice.gov.uk
