# TODO: get information elsewhere to avoid doubling up
DUCKDB_COLUMNS_WITH_TYPES = [
    ("match_id", "VARCHAR"),
    ("source_system", "VARCHAR"),
    ("source_system_id", "VARCHAR"),
    ("master_defendant_id", "VARCHAR"),
    ("first_name", "VARCHAR"),
    ("middle_names", "VARCHAR"),
    ("last_name", "VARCHAR"),
    ("date_of_birth", "DATE"),
    ("first_name_aliases", "TEXT[]"),
    ("last_name_aliases", "TEXT[]"),
    ("date_of_birth_aliases", "DATE[]"),
    ("postcodes", "TEXT[]"),
    ("cros", "TEXT[]"),
    ("pncs", "TEXT[]"),
    ("sentence_dates", "DATE[]"),
    ("override_marker", "VARCHAR"),
    ("override_scopes", "TEXT[]"),
]
